### ISSUE TITLE
Cant Install Teamspeak

### ISSUE THREAD

**Issue by l3ackEyeD** [ninelore/armaonlinux#22]
1. Configuring config
2. run ./Arma3Helper.sh install 

`Proton: Upgrading prefix from None to 7.0-100 (/home/phil/.steam/steam/steamapps/compatdata/107410/)
Traceback (most recent call last):
  File "/home/phil/.steam/steam/steamapps/common/Proton 7.0/proton", line 1508, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/phil/.steam/steam/steamapps/common/Proton 7.0/proton", line 1303, in init_session
    g_compatdata.setup_prefix()
  File "/home/phil/.steam/steam/steamapps/common/Proton 7.0/proton", line 846, in setup_prefix
    self.update_builtin_libs(builtin_dll_copy)
  File "/home/phil/.steam/steam/steamapps/common/Proton 7.0/proton", line 671, in update_builtin_libs
    with open(self.tracked_files_file, "r") as tracked_files:
FileNotFoundError: [Errno 2] No such file or directory: '/home/phil/.steam/steam/steamapps/compatdata/107410/tracked_files'
`

**Comment by ninelore** [comment]
You need to run Arma before starting Teamspeak. 

The error also tells me you never started Arma (with that prefix) before.

**Comment by l3ackEyeD** [comment]
I did start Arma before trying to install TS into its directory. Yet the error still exist. Anyway thanks for the help
