### ISSUE TITLE
Config file doesn't work

### ISSUE THREAD

**Issue by cachandlerdev** [ninelore/armaonlinux#27]
I just thought I'd create an issue pointing out that the `config` file doesn't seem to be working properly, and that the values have to be set directly in the script itself.

In my case, this was the error message I kept getting last week when I tried to change the config file. However, when I explicitly set the same values inside `Arma3Helper.sh`, the installation worked fine.
```bash
PROTON_OFFICIAL_VERSION="8.0"
COMPAT_DATA_PATH="/mnt/primary-storage/Games/Steam/steamapps/compatdata/107410"
STEAM_LIBRARY_PATH="/mnt/primary-storage/Games/Steam/steamapps"
PROTON_CUSTOM_VERSION=""
```
```bash
./Arma3Helper.sh install ~/Downloads/TeamSpeak3-Client-win64-3.6.1.exe
Trying to install Teamspeak with provided file
INSTALL TEAMSPEAK FOR ALL USERS AND LEAVE THE PATH DEFAULT!!! 

Proton: Upgrading prefix from None to 8.0-103 (/home/cachandler/.steam/steam/steamapps/compatdata/107410/)
Traceback (most recent call last):
  File "/home/cachandler/.steam/steam/steamapps/common/Proton 8.0/proton", line 1710, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/cachandler/.steam/steam/steamapps/common/Proton 8.0/proton", line 1502, in init_session
    g_compatdata.setup_prefix()
  File "/home/cachandler/.steam/steam/steamapps/common/Proton 8.0/proton", line 858, in setup_prefix
    self.update_builtin_libs(builtin_dll_copy)
  File "/home/cachandler/.steam/steam/steamapps/common/Proton 8.0/proton", line 679, in update_builtin_libs
    with open(self.tracked_files_file, "r") as tracked_files:
FileNotFoundError: [Errno 2] No such file or directory: '/home/cachandler/.steam/steam/steamapps/compatdata/107410/tracked_files'
```

**Comment by NickDeBeenSAE** [comment]
Yeah, I have a similar issue.

But its with the version of Wine the script calls.

It expects version 8.0.2, but version 7.8.2 is used, causing a mismatch.

Wine version 9 is available as of now.

And before all of these problems, I had the game working perfectly on Wine version 9.0.1.

Please see, and open to view below:

[message-2.txt](https://github.com/user-attachments/files/16825076/message-2.txt)

**Comment by ninelore** [comment]
Not a similar issue if at all. Sounds just misconfigured.

**Comment by NickDeBeenSAE** [comment]
Buts its not.

**Comment by NickDeBeenSAE** [comment]
All prefixes are the defaults as always.

**Comment by NickDeBeenSAE** [comment]
Its a version mismatch because the script is using an older version of Wine.

**Comment by NickDeBeenSAE** [comment]
I set them to the same defaults as I had them before I updated the script.

**Comment by NickDeBeenSAE** [comment]
> I just thought I'd create an issue pointing out that the `config` file doesn't seem to be working properly, and that the values have to be set directly in the script itself.
> 
> In my case, this was the error message I kept getting last week when I tried to change the config file. However, when I explicitly set the same values inside `Arma3Helper.sh`, the installation worked fine.
> 
> ```shell
> PROTON_OFFICIAL_VERSION="8.0"
> COMPAT_DATA_PATH="/mnt/primary-storage/Games/Steam/steamapps/compatdata/107410"
> STEAM_LIBRARY_PATH="/mnt/primary-storage/Games/Steam/steamapps"
> PROTON_CUSTOM_VERSION=""
> ```
> 
> ```shell
> ./Arma3Helper.sh install ~/Downloads/TeamSpeak3-Client-win64-3.6.1.exe
> Trying to install Teamspeak with provided file
> INSTALL TEAMSPEAK FOR ALL USERS AND LEAVE THE PATH DEFAULT!!! 
> 
> Proton: Upgrading prefix from None to 8.0-103 (/home/cachandler/.steam/steam/steamapps/compatdata/107410/)
> Traceback (most recent call last):
>   File "/home/cachandler/.steam/steam/steamapps/common/Proton 8.0/proton", line 1710, in <module>
>     g_session.init_session(sys.argv[1] != "runinprefix")
>   File "/home/cachandler/.steam/steam/steamapps/common/Proton 8.0/proton", line 1502, in init_session
>     g_compatdata.setup_prefix()
>   File "/home/cachandler/.steam/steam/steamapps/common/Proton 8.0/proton", line 858, in setup_prefix
>     self.update_builtin_libs(builtin_dll_copy)
>   File "/home/cachandler/.steam/steam/steamapps/common/Proton 8.0/proton", line 679, in update_builtin_libs
>     with open(self.tracked_files_file, "r") as tracked_files:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/cachandler/.steam/steam/steamapps/compatdata/107410/tracked_files'
> ```

Hey, wait a minute, this is pretty much what happened to me.

**Comment by ninelore** [comment]
Its not. Stop spamming here

**Comment by ninelore** [comment]
No Feedback, assuming resolved
